### ISSUE TITLE
Dear why your project can only recognize the default pic in "/pictures" folder? 

### ISSUE THREAD

**Issue by CreateSun** [ZhangHuan95/LPR#3]
I try to use some img from Internet, But no one could be recognized.

**Comment by ZhangHuan95** [comment]
是的，这里只用了最简单基于像素点的模板匹配，只做示例。这一步你可以使用OCR，或者训练你自己的神经网络去识别字符。
这篇文章的主要目的是介绍传统基于图像的车牌识别的基本流程。其中每个步骤你都可以去找更加行之有效的方法。
